# Generated by Django 3.1.3 on 2020-11-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_veiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='nome',
        ),
    ]
