# Generated by Django 3.1.3 on 2020-11-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_veiculo_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='candidate',
            new_name='cidade',
        ),
    ]
